[engine]
name = 'Curloz Engine'
refreshrate = 120
version_major = 0
version_minor = 7
version_patch = 0
vsync = false

[physics]
enablesleep = false
substepcount = 4
timestep = 0.0167

[renderer]
msaa = 4
triple_buffering = true

    [renderer.post_process]
    bloom_filter_radius = 0.0030000000260770321
    bloom_strength = 0.14599999785423279
    chromatic_aberration = 0.004999999888241291
    exposure = 1.0
    vignette_end = 2.0
    vignette_far = 2.0
    vignette_near = 0.89999997615814209

[window]
fullscreen = false
height = 600
width = 800