[engine]
name = "Curloz Engine"
version_major = 0
version_minor = 5
version_patch = 0

[window]
width = 800
height = 600
vsync = false
refreshrate = 120
triplebuffering = true

[physics]
substepcount = 4
timestep = 0.0167 # 1.0/60.0
enablesleep = false