[engine]
name = "Curloz Engine"
version_major = 0
version_minor = 3
version_patch = 6

[window]
width = 800
height = 600
vsync = false
refreshrate = 120
triplebuffering = true

[physics]
substepcount = 4
reversetimestep = 0.0167 # 1.0/60.0
enablesleep = false